In [1]:
#Importing Libraries 
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# Project folders

NOTEBOOK_DIR = Path.cwd()

PROJECT_DIR = NOTEBOOK_DIR.parent

RAW_DIR = PROJECT_DIR / "raw"

PROCESSED_DIR = PROJECT_DIR / "processed"

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Project folder:")
print(PROJECT_DIR)

print("\nRaw folder:")
print(RAW_DIR)

print("\nProcessed folder:")
print(PROCESSED_DIR)

Project folder:
C:\Users\NAYAN\Desktop\Traffic Accident Engine

Raw folder:
C:\Users\NAYAN\Desktop\Traffic Accident Engine\raw

Processed folder:
C:\Users\NAYAN\Desktop\Traffic Accident Engine\processed

In [3]:
# Find Excel files

excel_files = list(RAW_DIR.glob("*.xlsx"))

print("Excel files found:\n")

for file in excel_files:
    print(" -", file.name)

print("\nTotal files:", len(excel_files))

Excel files found:

 - 2022 dataset.xlsx
 - 4.1 opencity.xlsx
 - 4.2 opencity.xlsx
 - 4.3  opencity(citywise).xlsx

Total files: 4

In [4]:
# Find files automatically

file_4_1 = next(
    (f for f in excel_files if f.name.lower().startswith("4.1")),
    None
)

file_4_2 = next(
    (f for f in excel_files if f.name.lower().startswith("4.2")),
    None
)

file_4_3 = next(
    (f for f in excel_files if f.name.lower().startswith("4.3")),
    None
)

file_2022 = next(
    (f for f in excel_files if "2022" in f.name.lower()),
    None
)


# Check files

if file_4_1 is None:
    raise FileNotFoundError("4.1 OpenCity Excel file not found.")

if file_4_2 is None:
    raise FileNotFoundError("4.2 OpenCity Excel file not found.")

if file_4_3 is None:
    raise FileNotFoundError("4.3 OpenCity Excel file not found.")

if file_2022 is None:
    raise FileNotFoundError("2022 Excel file not found.")


# Load files

df_4_1 = pd.read_excel(file_4_1)

df_4_2 = pd.read_excel(file_4_2)

df_4_3 = pd.read_excel(file_4_3)

df_2022 = pd.read_excel(file_2022)


print("All four datasets loaded successfully.")

print("\n4.1:", df_4_1.shape)

print("4.2:", df_4_2.shape)

print("4.3:", df_4_3.shape)

print("2022:", df_2022.shape)

All four datasets loaded successfully.

4.1: (19, 3)
4.2: (19, 8)
4.3: (100, 11)
2022: (100, 15)

In [5]:
#Inspect Datasets
datasets = {
    "4.1 Road User Deaths": df_4_1,
    "4.2 Collision Types": df_4_2,
    "4.3 Citywise": df_4_3,
    "2022 Traffic": df_2022
}

for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    print("\nColumn names:")
    print(df.columns.tolist())

    print("\nFirst 3 rows:")
    display(df.head(3))

======================================================================
4.1 Road User Deaths
======================================================================
Rows: 19
Columns: 3

Column names:
['Category', '2022 Deaths', '% Change in Deaths']

First 3 rows:

         Category 2022 Deaths  % Change in Deaths
0      Pedestrian       32825                12.7
1  share in Total          20                 NaN
2        Bicycles        4836                 2.8

======================================================================
4.2 Collision Types
======================================================================
Rows: 19
Columns: 8

Column names:
['_id', 'Type of collision', '2022 Accidents', '2022 Killed', '2022 Injured', '% Change in Accidents', '%Change in Killed', '% Change in Injured']

First 3 rows:

,_id,Type of collision,2022 Accidents,2022 Killed,2022 Injured,% Change in Accidents,%Change in Killed,% Change in Injured
0,1,Hit and Run,67387,30486,54726,17.4,17.5,20.7
1,2,% share,14.6,18.1,12.3,NaN,NaN,NaN
2,3,With parked Vehicle,14139,6012,12666,21.8,22.1,22.9

======================================================================
4.3 Citywise
======================================================================
Rows: 100
Columns: 11

Column names:
['city_id', 'id', 'cities', 'accidents_2022', 'accidents_ranking_2022', 'deaths_2022', 'deaths_ranking_2022', 'injured_2022', 'injured_ranking_2022', 'city', 'city_key']

First 3 rows:

,city_id,id,cities,accidents_2022,accidents_ranking_2022,deaths_2022,deaths_ranking_2022,injured_2022,injured_ranking_2022,city,city_key
0,1,1,Agra,1029,60,548,9,795,74,Agra,Agra
1,2,2,Ahmedabad,1711,24,488,11,1305,46,Ahmedabad,Ahmedabad
2,3,3,Allahabad(Prayagraj),1370,38,603,6,886,70,Prayagraj,Prayagraj

======================================================================
2022 Traffic
======================================================================
Rows: 100
Columns: 15

Column names:
['city_id', 'city', 'road_accidents_cases', 'road_accidents_injured', 'road_accidents_died', 'railway_accidents_cases', 'railway_accidents_injured', 'railway_accidents_died', 'railway_crossing_accidents_cases', 'railway_crossing_accidents_injured', 'railway_crossing_accidents_died', 'total_traffic_accidents_cases', 'total_traffic_accidents_injured', 'total_traffic_accidents_died', 'city_key']

First 3 rows:

,city_id,city,road_accidents_cases,road_accidents_injured,road_accidents_died,railway_accidents_cases,railway_accidents_injured,railway_accidents_died,railway_crossing_accidents_cases,railway_crossing_accidents_injured,railway_crossing_accidents_died,total_traffic_accidents_cases,total_traffic_accidents_injured,total_traffic_accidents_died,city_key
0,1,Agra,729.0,91.0,698.0,66.0,0.0,47.0,11.0,0.0,11.0,806.0,91.0,756.0,Agra
1,2,Ahmedabad,1711.0,1305.0,488.0,40.0,0.0,41.0,0.0,0.0,0.0,1751.0,1305.0,529.0,Ahmedabad
2,3,Allahabad(Prayagraj),1370.0,886.0,603.0,0.0,0.0,0.0,0.0,0.0,0.0,1370.0,886.0,603.0,Prayagraj

In [6]:
#Standardize column names
def clean_column_names(df):

    df = df.copy()

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace("%", "percent", regex=False)
        .str.replace("-", "_", regex=False)
        .str.replace("/", "_", regex=False)
        .str.replace(" ", "_", regex=False)
        .str.replace("(", "", regex=False)
        .str.replace(")", "", regex=False)
        .str.replace(".", "", regex=False)
    )

    df.columns = (
        df.columns
        .str.replace(r"_+", "_", regex=True)
        .str.strip("_")
    )

    return df


df_4_1 = clean_column_names(df_4_1)

df_4_2 = clean_column_names(df_4_2)

df_4_3 = clean_column_names(df_4_3)

df_2022 = clean_column_names(df_2022)

print("Column names standardized.")

Column names standardized.

In [7]:
#Checking important columns
print("4.3 columns:")
print(df_4_3.columns.tolist())

print("\n2022 columns:")
print(df_2022.columns.tolist())

4.3 columns:
['city_id', 'id', 'cities', 'accidents_2022', 'accidents_ranking_2022', 'deaths_2022', 'deaths_ranking_2022', 'injured_2022', 'injured_ranking_2022', 'city', 'city_key']

2022 columns:
['city_id', 'city', 'road_accidents_cases', 'road_accidents_injured', 'road_accidents_died', 'railway_accidents_cases', 'railway_accidents_injured', 'railway_accidents_died', 'railway_crossing_accidents_cases', 'railway_crossing_accidents_injured', 'railway_crossing_accidents_died', 'total_traffic_accidents_cases', 'total_traffic_accidents_injured', 'total_traffic_accidents_died', 'city_key']

In [8]:
#Remove summary rows

# ---------- 4.1 ----------

if "category" in df_4_1.columns:

    df_4_1 = df_4_1[
        ~df_4_1["category"]
        .astype("string")
        .str.strip()
        .str.lower()
        .isin([
            "total",
            "share in total"
        ])
    ].copy()


# ---------- 4.2 ----------

if "type_of_collision" in df_4_2.columns:

    df_4_2 = df_4_2[
        ~df_4_2["type_of_collision"]
        .astype("string")
        .str.strip()
        .str.lower()
        .isin([
            "total",
            "% share"
        ])
    ].copy()


# ---------- 4.3 ----------

if "cities" in df_4_3.columns:

    df_4_3 = df_4_3[
        ~df_4_3["cities"]
        .astype("string")
        .str.strip()
        .str.lower()
        .isin([
            "total"
        ])
    ].copy()


# ---------- 2022 ----------

# Automatically find the State/UT/City column.
# This prevents the previous KeyError.

possible_2022_city_columns = [
    "state_ut_city",
    "state_ut_city_name",
    "state_city",
    "city"
]

city_column_2022 = None

for col in possible_2022_city_columns:

    if col in df_2022.columns:
        city_column_2022 = col
        break


if city_column_2022 is None:

    raise KeyError(
        "Could not find the city column in the 2022 dataset.\n\n"
        "Available columns are:\n"
        + "\n".join(df_2022.columns.tolist())
    )


print("2022 city column detected as:", city_column_2022)


summary_values = [
    "total (states)",
    "total (uts)",
    "total (all india)",
    "total (cities)"
]


df_2022 = df_2022[
    ~df_2022[city_column_2022]
    .astype("string")
    .str.strip()
    .str.lower()
    .isin(summary_values)
].copy()


print("\nSummary rows removed successfully.")

print("4.1 rows:", len(df_4_1))

print("4.2 rows:", len(df_4_2))

print("4.3 rows:", len(df_4_3))

print("2022 rows:", len(df_2022))

2022 city column detected as: city

Summary rows removed successfully.
4.1 rows: 9
4.2 rows: 9
4.3 rows: 100
2022 rows: 100

In [9]:
#Clean numeric columns
def clean_numeric_columns(df, columns):

    df = df.copy()

    for col in columns:

        if col in df.columns:

            df[col] = (
                df[col]
                .astype("string")
                .str.replace(",", "", regex=False)
                .str.replace("%", "", regex=False)
                .str.strip()
            )

            df[col] = pd.to_numeric(
                df[col],
                errors="coerce"
            )

    return df

In [10]:
#Applying numeric cleaning
numeric_4_1 = [
    "2022_deaths",
    "percent_change_in_deaths"
]


numeric_4_2 = [
    "2022_accidents",
    "2022_killed",
    "2022_injured",
    "percent_change_in_accidents",
    "percentchange_in_killed",
    "percent_change_in_injured"
]


numeric_4_3 = [
    "id",
    "accidents_2022",
    "accidents_ranking_2022",
    "deaths_2022",
    "deaths_ranking_2022",
    "injured_2022",
    "injured_ranking_2022"
]


numeric_2022 = [
    "sl_no",
    "road_accidents_cases",
    "road_accidents_injured",
    "road_accidents_died",
    "railway_accidents_cases",
    "railway_accidents_injured",
    "railway_accidents_died",
    "railway_crossing_accidents_cases",
    "railway_crossing_accidents_injured",
    "railway_crossing_accidents_died",
    "total_traffic_accidents_cases",
    "total_traffic_accidents_injured",
    "total_traffic_accidents_died"
]


df_4_1 = clean_numeric_columns(
    df_4_1,
    numeric_4_1
)

df_4_2 = clean_numeric_columns(
    df_4_2,
    numeric_4_2
)

df_4_3 = clean_numeric_columns(
    df_4_3,
    numeric_4_3
)

df_2022 = clean_numeric_columns(
    df_2022,
    numeric_2022
)

print("Numeric columns cleaned.")

Numeric columns cleaned.

In [11]:
#Cleaning Text
def clean_text_columns(df):

    df = df.copy()

    text_columns = df.select_dtypes(
        include=["object", "string"]
    ).columns

    for col in text_columns:

        df[col] = (
            df[col]
            .astype("string")
            .str.strip()
            .str.replace(
                r"\s+",
                " ",
                regex=True
            )
        )

    return df


df_4_1 = clean_text_columns(df_4_1)

df_4_2 = clean_text_columns(df_4_2)

df_4_3 = clean_text_columns(df_4_3)

df_2022 = clean_text_columns(df_2022)

print("Text values cleaned.")

Text values cleaned.

In [12]:
#Removing exact duplicate rows
print("Duplicates before removal:")

print("4.1:", df_4_1.duplicated().sum())

print("4.2:", df_4_2.duplicated().sum())

print("4.3:", df_4_3.duplicated().sum())

print("2022:", df_2022.duplicated().sum())


df_4_1 = df_4_1.drop_duplicates().copy()

df_4_2 = df_4_2.drop_duplicates().copy()

df_4_3 = df_4_3.drop_duplicates().copy()

df_2022 = df_2022.drop_duplicates().copy()


print("\nExact duplicate rows removed.")

Duplicates before removal:
4.1: 0
4.2: 0
4.3: 0
2022: 0

Exact duplicate rows removed.

In [13]:
#Standardize city names
CITY_MAPPING = {

    "Allahabad(Prayagraj)": "Prayagraj",

    "Prayagraj +": "Prayagraj",

    "Vizaq": "Visakhapatnam",

    "Vishakhapatnam": "Visakhapatnam",

    "Thiruvanthapuram": "Thiruvananthapuram",

    "Nasik": "Nashik",

    "Bangalore": "Bengaluru",

    "Vijayawada city": "Vijayawada",

    "Chandigarh (city)": "Chandigarh",

    "Delhi (city)": "Delhi"
}


# 4.3

df_4_3["city"] = (
    df_4_3["cities"]
    .astype("string")
    .str.strip()
    .replace(CITY_MAPPING)
)


# 2022

df_2022["city"] = (
    df_2022[city_column_2022]
    .astype("string")
    .str.strip()
    .replace(CITY_MAPPING)
)


print("City names standardized.")

City names standardized.

In [14]:
#Create city key
def create_city_key(series):

    return (
        series
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(
            r"\s+",
            " ",
            regex=True
        )
    )


df_4_3["city_key"] = create_city_key(
    df_4_3["city"]
)

df_2022["city_key"] = create_city_key(
    df_2022["city"]
)


print("City keys created.")

City keys created.

In [21]:
# Load the prepared 100-city OpenCity file

clean_100_file = RAW_DIR / "4.3 opencity(citywise).xlsx"

if not clean_100_file.exists():

    raise FileNotFoundError(
        "The file '4.3  opencity(citywise).xlsx' "
        "was not found in the raw folder."
    )


df_4_3 = pd.read_excel(
    clean_100_file
)

df_4_3 = clean_column_names(
    df_4_3
)


# Detect the city column

if "city" in df_4_3.columns:

    city_col_43 = "city"

elif "cities" in df_4_3.columns:

    city_col_43 = "cities"

else:

    raise KeyError(
        "City column not found in the 4.3 file."
    )


df_4_3["city"] = (
    df_4_3[city_col_43]
    .astype("string")
    .str.strip()
)


df_4_3["city_key"] = create_city_key(
    df_4_3["city"]
)


print("Clean 100-city OpenCity file loaded.")

print("Rows:", len(df_4_3))

print(
    "Unique cities:",
    df_4_3["city_key"].nunique()
)

Clean 100-city OpenCity file loaded.
Rows: 100
Unique cities: 100

In [22]:
if len(df_4_3) != 100:

    raise ValueError(
        f"STOP: 4.3 contains {len(df_4_3)} rows. "
        "Expected exactly 100."
    )


if df_4_3["city_key"].nunique() != 100:

    raise ValueError(
        "STOP: 4.3 does not contain exactly "
        "100 unique cities."
    )


print("==========================================")
print("4.3 VALIDATION PASSED")
print("Rows: 100")
print("Unique Cities: 100")
print("==========================================")

==========================================
4.3 VALIDATION PASSED
Rows: 100
Unique Cities: 100
==========================================

In [23]:
#Preparing Data
citywise_clean = df_4_3.copy()

print("Citywise data prepared.")

print(
    "Rows:",
    len(citywise_clean)
)

print(
    "Unique cities:",
    citywise_clean["city_key"].nunique()
)

Citywise data prepared.
Rows: 100
Unique cities: 100

In [24]:
#Preparing 2022 Data
traffic_clean = df_2022.copy()

print("2022 traffic data prepared.")

print(
    "Rows:",
    len(traffic_clean)
)

print(
    "Unique city keys:",
    traffic_clean["city_key"].nunique()
)

2022 traffic data prepared.
Rows: 100
Unique city keys: 100

In [25]:
#Removing 2022 duplicate city keys 
duplicate_2022 = (
    traffic_clean["city_key"]
    .duplicated()
    .sum()
)

print(
    "Duplicate 2022 city keys:",
    duplicate_2022
)


traffic_clean = (
    traffic_clean
    .drop_duplicates(
        subset=["city_key"],
        keep="first"
    )
    .copy()
)


print(
    "2022 rows after duplicate city handling:",
    len(traffic_clean)
)

Duplicate 2022 city keys: 0
2022 rows after duplicate city handling: 100

In [26]:
#Creating Road Danger Index 
accident_cases = pd.to_numeric(
    traffic_clean["road_accidents_cases"],
    errors="coerce"
)

accident_deaths = pd.to_numeric(
    traffic_clean["road_accidents_died"],
    errors="coerce"
)


traffic_clean["road_danger_index"] = (
    accident_deaths
    .div(accident_cases)
    .mul(100)
    .where(
        accident_cases.gt(0)
    )
    .round(2)
)


print("Road Danger Index created.")

Road Danger Index created.

In [27]:
#Creating Road Danger Category
def danger_category(value):

    if pd.isna(value):
        return "N/A"

    if value < 5:
        return "Low"

    elif value < 10:
        return "Medium"

    elif value < 20:
        return "High"

    else:
        return "Very High"


traffic_clean["road_danger_category"] = (
    traffic_clean["road_danger_index"]
    .apply(danger_category)
)


print("Road Danger Category created.")

Road Danger Category created.

In [28]:
traffic_clean["time_of_day_category"] = "N/A"

traffic_clean["weather_risk_score"] = np.nan

traffic_clean["weather_risk_category"] = "N/A"


print("Additional analysis columns created.")

Additional analysis columns created.

In [29]:
#Checking Matching Cities
cities_43 = set(
    citywise_clean["city_key"]
)

cities_2022 = set(
    traffic_clean["city_key"]
)


matching = (
    cities_43.intersection(
        cities_2022
    )
)

missing_2022 = (
    cities_43 - cities_2022
)


print("Total 4.3 cities:", len(cities_43))

print(
    "Cities with 2022 data:",
    len(matching)
)

print(
    "Cities without 2022 data:",
    len(missing_2022)
)


print("\nCities without 2022 data:")

for city in sorted(missing_2022):
    print("-", city)

Total 4.3 cities: 100
Cities with 2022 data: 100
Cities without 2022 data: 0

Cities without 2022 data:

In [30]:
#Final Merge 
# 4.3 is the BASE table.
# Therefore all 100 cities remain.

traffic_for_merge = traffic_clean.drop(
    columns=["city"],
    errors="ignore"
)


master_df = pd.merge(
    citywise_clean,
    traffic_for_merge,
    on="city_key",
    how="left",
    validate="one_to_one"
)


print("Final merge completed.")

Final merge completed.

In [31]:
#Checking Final Result 
print("=" * 70)
print("FINAL MERGE CHECK")
print("=" * 70)

print(
    "Rows:",
    len(master_df)
)

print(
    "Unique cities:",
    master_df["city"].nunique()
)

print(
    "Duplicate city keys:",
    master_df["city_key"].duplicated().sum()
)

======================================================================
FINAL MERGE CHECK
======================================================================
Rows: 100
Unique cities: 100
Duplicate city keys: 0

In [32]:
#Stop if anything is wrong
if len(master_df) != 100:

    raise ValueError(
        f"STOP: Final dataset has {len(master_df)} rows. "
        "Expected exactly 100."
    )


if master_df["city"].nunique() != 100:

    raise ValueError(
        "STOP: Final dataset does not have "
        "100 unique cities."
    )


if master_df["city_key"].duplicated().sum() != 0:

    raise ValueError(
        "STOP: Duplicate cities found."
    )


print("==========================================")
print("100 CITY CHECK PASSED")
print("==========================================")

==========================================
100 CITY CHECK PASSED
==========================================

In [33]:
# Check the actual columns after merge
print("Columns in master_df:")
print(master_df.columns.tolist())



if "accidents_2022" in master_df.columns:
    master_df["citywise_data_available"] = np.where(
        master_df["accidents_2022"].notna(),
        "Yes",
        "No"
    )
else:
    master_df["citywise_data_available"] = "No"



if "road_accidents_cases" in master_df.columns:
    master_df["traffic_2022_data_available"] = np.where(
        master_df["road_accidents_cases"].notna(),
        "Yes",
        "No"
    )
else:
    master_df["traffic_2022_data_available"] = "No"


# ------------------------------------------------------------
# 3. Overall availability
# ------------------------------------------------------------

master_df["data_availability"] = np.where(
    (master_df["citywise_data_available"] == "Yes") &
    (master_df["traffic_2022_data_available"] == "Yes"),
    "Both Sources",
    np.where(
        master_df["citywise_data_available"] == "Yes",
        "OpenCity Only",
        np.where(
            master_df["traffic_2022_data_available"] == "Yes",
            "2022 Traffic Only",
            "No Data"
        )
    )
)

print("\nAvailability flags added successfully.")

print(
    master_df[
        [
            "city",
            "citywise_data_available",
            "traffic_2022_data_available",
            "data_availability"
        ]
    ].head(10)
)

Columns in master_df:
['city_id_x', 'id', 'cities', 'accidents_2022', 'accidents_ranking_2022', 'deaths_2022', 'deaths_ranking_2022', 'injured_2022', 'injured_ranking_2022', 'city', 'city_key', 'city_id_y', 'road_accidents_cases', 'road_accidents_injured', 'road_accidents_died', 'railway_accidents_cases', 'railway_accidents_injured', 'railway_accidents_died', 'railway_crossing_accidents_cases', 'railway_crossing_accidents_injured', 'railway_crossing_accidents_died', 'total_traffic_accidents_cases', 'total_traffic_accidents_injured', 'total_traffic_accidents_died', 'road_danger_index', 'road_danger_category', 'time_of_day_category', 'weather_risk_score', 'weather_risk_category']

Availability flags added successfully.
               city citywise_data_available traffic_2022_data_available  \
0              Agra                     Yes                         Yes
1         Ahmedabad                     Yes                         Yes
2         Prayagraj                     Yes                         Yes
3          Amritsar                     Yes                         Yes
4  Asansol Durgapur                     Yes                          No
5        Aurangabad                     Yes                         Yes
6         Bengaluru                     Yes                         Yes
7            Bhopal                     Yes                         Yes
8        Chandigarh                     Yes                         Yes
9           Chennai                     Yes                         Yes

  data_availability
0      Both Sources
1      Both Sources
2      Both Sources
3      Both Sources
4     OpenCity Only
5      Both Sources
6      Both Sources
7      Both Sources
8      Both Sources
9      Both Sources

In [34]:
#Adding year and source 
master_df["data_year"] = 2022

master_df["data_source"] = (
    "OpenCity + 2022 Traffic Accident Dataset"
)

print("Year and source added.")

Year and source added.

In [35]:
#Converting missing value to N/A
# Convert to object first so N/A can be stored safely

master_df = master_df.astype(object).where(
    master_df.notna(),
    "N/A"
)


print("Missing values replaced with N/A.")

Missing values replaced with N/A.

In [36]:
#Checking blank cells
blank_cells = (
    master_df.isna()
    .sum()
    .sum()
)

print(
    "Blank cells:",
    blank_cells
)


if blank_cells != 0:

    raise ValueError(
        "STOP: Blank cells still exist."
    )


print("✅ No blank cells.")

Blank cells: 0
✅ No blank cells.

In [37]:
#Checking Duplicate Rows 
duplicate_rows = (
    master_df.duplicated()
    .sum()
)

duplicate_cities = (
    master_df["city_key"]
    .duplicated()
    .sum()
)


print(
    "Duplicate rows:",
    duplicate_rows
)

print(
    "Duplicate cities:",
    duplicate_cities
)


if duplicate_rows != 0:

    raise ValueError(
        "STOP: Duplicate rows found."
    )


if duplicate_cities != 0:

    raise ValueError(
        "STOP: Duplicate cities found."
    )


print("✅ No duplicates.")

Duplicate rows: 0
Duplicate cities: 0
✅ No duplicates.

In [38]:
#Final Validation
print("\n")
print("=" * 70)
print("FINAL VALIDATION")
print("=" * 70)

print(
    "Total rows:",
    len(master_df)
)

print(
    "Total columns:",
    len(master_df.columns)
)

print(
    "Unique cities:",
    master_df["city"].nunique()
)

print(
    "Duplicate cities:",
    master_df["city"].duplicated().sum()
)

print(
    "Duplicate rows:",
    master_df.duplicated().sum()
)

print(
    "Blank cells:",
    master_df.isna().sum().sum()
)

======================================================================
FINAL VALIDATION
======================================================================
Total rows: 100
Total columns: 34
Unique cities: 100
Duplicate cities: 0
Duplicate rows: 0
Blank cells: 0

In [39]:
# Saving 4.1

df_4_1.to_excel(
    PROCESSED_DIR / "4.1 opencity.xlsx",
    index=False
)


# Saving 4.2

df_4_2.to_excel(
    PROCESSED_DIR / "4.2 opencity.xlsx",
    index=False
)


# Saving 4.3

df_4_3.to_excel(
    PROCESSED_DIR / "4.3 opencity(citywise).xlsx",
    index=False
)


# Saving 2022

df_2022.to_excel(
    PROCESSED_DIR / "2022 dataset.xlsx",
    index=False
)


print("All cleaned datasets saved successfully.")

All cleaned datasets saved successfully.

In [40]:
# Saving Final Master Excel

master_excel = (
    PROCESSED_DIR /
    "Master Traffic Accident Engine.xlsx"
)


master_df.to_excel(
    master_excel,
    index=False
)


print("MASTER EXCEL SAVED:")
print(master_excel)

MASTER EXCEL SAVED:
C:\Users\NAYAN\Desktop\Traffic Accident Engine\processed\Master Traffic Accident Engine.xlsx

In [41]:
# Final Quality Report

print("=" * 70)
print("TRAFFIC ACCIDENT DATA CLEANING COMPLETED")
print("=" * 70)


print("\nMASTER DATASET")
print("-" * 50)

print(
    "Rows:",
    master_df.shape[0]
)

print(
    "Columns:",
    master_df.shape[1]
)

print(
    "Unique cities:",
    master_df["city"].nunique()
)

print(
    "Duplicate rows:",
    master_df.duplicated().sum()
)

print(
    "Duplicate cities:",
    master_df["city"].duplicated().sum()
)


print("\nROAD DANGER CATEGORY")
print("-" * 50)

print(
    master_df[
        "road_danger_category"
    ].value_counts()
)


print("\nTIME OF DAY")
print("-" * 50)

print(
    master_df[
        "time_of_day_category"
    ].value_counts()
)


print("\nWEATHER")
print("-" * 50)

print(
    master_df[
        "weather_risk_category"
    ].value_counts()
)


print("\nOUTPUT FOLDER")
print("-" * 50)

print(PROCESSED_DIR)


print("\nMASTER EXCEL")
print("-" * 50)

print(master_excel)


print("\n" + "=" * 70)
print("CLEANING PIPELINE COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
TRAFFIC ACCIDENT DATA CLEANING COMPLETED
======================================================================

MASTER DATASET
--------------------------------------------------
Rows: 100
Columns: 34
Unique cities: 100
Duplicate rows: 0
Duplicate cities: 0

ROAD DANGER CATEGORY
--------------------------------------------------
road_danger_category
N/A          48
Very High    37
Medium        8
High          7
Name: count, dtype: int64

TIME OF DAY
--------------------------------------------------
time_of_day_category
N/A    100
Name: count, dtype: int64

WEATHER
--------------------------------------------------
weather_risk_category
N/A    100
Name: count, dtype: int64

OUTPUT FOLDER
--------------------------------------------------
C:\Users\NAYAN\Desktop\Traffic Accident Engine\processed

MASTER EXCEL
--------------------------------------------------
C:\Users\NAYAN\Desktop\Traffic Accident Engine\processed\Master Traffic Accident Engine.xlsx

======================================================================
CLEANING PIPELINE COMPLETED SUCCESSFULLY
======================================================================